import { Component, Inject } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Title } from '@angular/platform-browser';
import { NgForm, FormGroup, FormControl, Validators, FormBuilder, FormArray } from '@angular/forms';
import { Validation } from '../validators/validation-helper.provider';

@Component({
  selector: 'app-membership',
  templateUrl: './membership.component.html',
  styleUrls: ['./membership.component.scss']
})
export class MembershipComponent {

  private http: HttpClient;
  private baseUrl: string;
  private formBuilder: FormBuilder;

  public sending: boolean = false;
  public messageSent: boolean = false;
  public validation: Validation;
  public messageStatus: FormStatus = FormStatus.ShowForm;

  public messageStatusEnum = FormStatus;
  public form: FormGroup;

  public breeds: string[] = ["Affenpinscher",
    "Afghan Hound",
    "Afghan Shepherd",
    "Aidi",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Akita Inu",
    "Alano Español",
    "Alaskan husky",
    "Alaskan Klee Kai",
    "Alaskan Malamute",
    "Alaunt",
    "Alopekis",
    "Alpine Dachsbracke",
    "Alpine Mastiff",
    "Alpine Spaniel",
    "Am Staff",
    "American Akita",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Coonhound",
    "American English Coonhound",
    "American Eskimo Dog",
    "American Foxhound",
    "American Hairless Terrier",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Anatolian Shepherd Dog",
    "Andalusian Hound",
    "Anglo-Français de Petite Vénerie",
    "Appenzeller Sennenhund",
    "Appenzeller Sennenhunde",
    "Ariegeois",
    "Armant",
    "Armenian Gampr dog",
    "Artois Hound",
    "Australian Cattle",
    "Australian Cattle Dog",
    "Australian Kelpie",
    "Australian Shepherd",
    "Australian Silky Terrier",
    "Australian Stumpy Tail Cattle Dog[10]",
    "Australian Terrier",
    "Austrian Black and Tan Hound",
    "Austrian Pinscher",
    "Azawakh",
    "Bakharwal Dog",
    "Barbet",
    "Basenji",
    "Basque Shepherd Dog",
    "Basset Artésien Normand",
    "Basset Bleu de Gascogne",
    "Basset Fauve de Bretagne",
    "Basset Griffon Vendéen, Grand",
    "Basset Griffon Vendéen, Petit",
    "Basset Hound",
    "Bavarian Mountain Hound",
    "Beagle",
    "Beagle-Harrier",
    "Bearded Collie",
    "Beauceron",
    "Bedlington Terrier",
    "Belgian Laekenois",
    "Belgian Malinois",
    "Belgian Sheepdog",
    "Belgian Shepherd Dog (Groenendael)",
    "Belgian Shepherd Dog (Laekenois)",
    "Belgian Shepherd Dog (Malinois)",
    "Belgian Shepherd Dog (Tervuren)",
    "Belgian Tervuren",
    "Bergamasco",
    "Bergamasco Shepherd",
    "Berger Blanc Suisse",
    "Berger Picard",
    "Bernedoodle",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Bichon Frisé",
    "Biewer Terrier",
    "Billy",
    "Black &amp; Tan Coonhound",
    "Black and Tan Coonhound",
    "Black and Tan Virginia Foxhound",
    "Black Mouth Cur",
    "Black Norwegian Elkhound",
    "Black Russian Terrier",
    "Bleu de Gascogne, Grand",
    "Bleu de Gascogne, Petit",
    "Bloodhound",
    "Blue Heeler",
    "Blue Lacy",
    "Blue Paul Terrier",
    "Blue Picardy Spaniel",
    "Bluetick Coonhound",
    "Boerboel",
    "Bohemian Shepherd",
    "Bolognese",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Bosnian Coarse-haired Hound",
    "Boston Terrier",
    "Bouvier des Ardennes",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Bracco Italiano",
    "Braque d'Auvergne",
    "Braque de l'Ariege",
    "Braque du Bourbonnais",
    "Braque du Puy",
    "Braque Francais",
    "Braque Saint-Germain",
    "Brazilian Dogo",
    "Brazilian Terrier",
    "Briard",
    "Briquet Griffon Vendéen",
    "Brittany",
    "Broholmer",
    "Bruno Jura Hound",
    "Brussels Griffon",
    "Bucovina Shepherd Dog",
    "Bull and Terrier",
    "Bull Terrier",
    "Bulldog",
    "Bulldog - American",
    "Bullenbeisser",
    "Bullmastiff",
    "Bully Kutta",
    "Cairn Terrier",
    "Canaan Dog",
    "Canadian Eskimo Dog",
    "Cane Corso",
    "Cantabrian Water Dog",
    "Cão da Serra de Aires",
    "Cão de Castro Laboreiro",
    "Cão de Gado Transmontano",
    "Cão Fila de São Miguel",
    "Cardigan Welsh Corgi",
    "Carolina Dog",
    "Carpathian Shepherd Dog",
    "Catahoula Leopard Dog",
    "Catalan Sheepdog",
    "Caucasian Shepherd Dog",
    "Cavalier King Charles",
    "Cavalier King Charles Spaniel",
    "Central Asian Shepherd Dog",
    "Cesky Fousek",
    "Cesky Terrier",
    "Chesapeake Bay Retriever",
    "Chien Français Blanc et Noir",
    "Chien Français Blanc et Orange",
    "Chien Français Tricolore",
    "Chien-gris",
    "Chihuahua",
    "Chilean Fox Terrier",
    "Chinese Chongqing Dog",
    "Chinese Crested",
    "Chinese Crested Dog",
    "Chinese Imperial Dog",
    "Chinese Shar-Pei",
    "Chinook",
    "Chippiparai",
    "Chow Chow",
    "Cierny Sery",
    "Cimarrón Uruguayo",
    "Cirneco dell'Etna",
    "Clumber Spaniel",
    "Cockapoo",
    "Cocker Spaniel",
    "Cocker Spaniel - American",
    "Cocker Spaniel - English",
    "Collie",
    "Collie, Rough",
    "Collie, Smooth",
    "Combai",
    "Cordoba Fighting Dog",
    "Coton de Tulear",
    "Cretan Hound",
    "Croatian Sheepdog",
    "Cumberland Sheepdog",
    "Curly-Coated Retriever",
    "Cursinu",
    "Czechoslovakian Wolfdog",
    "Dachshund",
    "Dalmatian",
    "Dandie Dinmont Terrier",
    "Danish-Swedish Farmdog",
    "Deutsche Bracke",
    "Doberman Pinscher",
    "Dogo Argentino",
    "Dogo Cubano",
    "Dogue de Bordeaux",
    "Drentse Patrijshond",
    "Drever",
    "Dunker",
    "Dutch Shepherd",
    "Dutch Smoushond",
    "East European Shepherd",
    "East Siberian Laika",
    "Elo",
    "English Bulldog",
    "English Cocker Spaniel",
    "English Foxhound",
    "English Pointer",
    "English Setter",
    "English Shepherd",
    "English Springer Spaniel",
    "English Toy Spaniel",
    "English Toy Terrier (Black &amp; Tan)",
    "English Water Spaniel",
    "English White Terrier",
    "Entlebucher Mountain Dog",
    "Estonian Hound",
    "Estrela Mountain Dog",
    "Eurasier",
    "Eurohound",
    "Field Spaniel",
    "Fila Brasileiro",
    "Finnish Hound",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat Coated Retriever",
    "Flat-Coated Retriever",
    "Fox Terrier",
    "Fox Terrier, Smooth",
    "Fox Terrier, Wire",
    "French Brittany",
    "French Bulldog",
    "French Spaniel",
    "Gaddi Dog",
    "Galgo Español",
    "Galician Cattle Dog",
    "Garafian Shepherd",
    "Gascon Saintongeois",
    "Georgian Shepherd Dog",
    "German Longhaired Pointer",
    "German Pinscher",
    "German Roughhaired Pointer",
    "German Shepherd",
    "German Shepherd Dog",
    "German Shorthaired Pointer",
    "German Spaniel",
    "German Spitz",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Goldador",
    "Golden Retriever",
    "Goldendoodle",
    "Gordon Setter",
    "Gran Mastín de Borínquen",
    "Grand Anglo-Français Blanc et Noir",
    "Grand Anglo-Français Blanc et Orange",
    "Grand Anglo-Français Tricolore",
    "Grand Griffon Vendéen",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Greek Harehound",
    "Greenland Dog",
    "Greyhound",
    "Griffon Bleu de Gascogne",
    "Griffon Bruxellois",
    "Griffon Fauve de Bretagne",
    "Griffon Nivernais",
    "Guatemalan Dogo",
    "Hamiltonstövare",
    "Hanover Hound",
    "Hare Indian Dog",
    "Harrier",
    "Havana Silk Dog",
    "Havanese",
    "Hawaiian Poi Dog",
    "Himalayan Sheepdog",
    "Hokkaido",
    "Hortaya Borzaya",
    "Hovawart",
    "Huntaway",
    "Hygenhund",
    "Ibizan Hound",
    "Icelandic Sheepdog",
    "Indian pariah dog",
    "Indian Spitz",
    "Irish Red and White Setter",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Istrian Coarse-haired Hound",
    "Istrian Shorthaired Hound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Jagdterrier",
    "Jämthund",
    "Japanese Chin",
    "Japanese Spitz",
    "Japanese Terrier",
    "Kai Ken",
    "Kaikadi",
    "Kangal Dog",
    "Kanni",
    "Karakachan Dog",
    "Karelian Bear Dog",
    "Karst Shepherd",
    "Keeshond",
    "Kerry Beagle",
    "Kerry Blue Terrier",
    "King Charles Spaniel",
    "King Shepherd",
    "Kintamani",
    "Kishu Ken",
    "Komondor",
    "Kooikerhondje",
    "Koolie",
    "Korean Jindo",
    "Korean Jindo Dog",
    "Kromfohrländer",
    "Kumaon Mastiff",
    "Kunming Wolfdog",
    "Kuri",
    "Kuvasz",
    "Kyi-Leo",
    "Labradoodle",
    "Labrador Husky",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Lapponian Herder",
    "Leonberger",
    "Lhasa Apso",
    "Lithuanian Hound",
    "Lowchen",
    "Löwchen",
    "Mackenzie River Husky",
    "Magyar Agár",
    "Mahratta Greyhound",
    "Majorca Ratter",
    "Majorca Shepherd Dog",
    "Maltese",
    "Maltese Shih Tzu",
    "Maltipoo",
    "Manchester Terrier",
    "Maremma Sheepdog",
    "Mastiff",
    "McNab",
    "Mexican Hairless Dog",
    "Miniature American Shepherd",
    "Miniature Australian Shepherd",
    "Miniature Bull Terrier",
    "Miniature Fox Terrier",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Miniature Shar Pei",
    "Molossus",
    "Molossus of Epirus",
    "Montenegrin Mountain Hound",
    "Moscow Watchdog",
    "Moscow Water Dog",
    "Mountain Cur",
    "Mucuchies",
    "Mudhol Hound",
    "Mudi",
    "Münsterländer, Large",
    "Münsterländer, Small",
    "Mutt",
    "NAID Breed",
    "Neapolitan Mastiff",
    "New Zealand Heading Dog",
    "Newfoundland",
    "Norfolk Spaniel",
    "Norfolk Terrier",
    "Norrbottenspets",
    "North Country Beagle",
    "Northern Inuit Dog",
    "Norwegian Buhund",
    "Norwegian Elkhound",
    "Norwegian Lundehund",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling",
    "Nova Scotia Duck Tolling Retriever",
    "Old Croatian Sighthound",
    "Old Danish Pointer",
    "Old English Sheepdog",
    "Old English Terrier",
    "Old German Shepherd Dog",
    "Old Time Farm Shepherd",
    "Olde English Bulldogge",
    "Otterhound",
    "Pachon Navarro",
    "Paisley Terrier",
    "Pandikona Hunting Dog",
    "Papillon",
    "Parson Russell Terrier",
    "Patterdale Terrier",
    "Peekapoo",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Perdiguero de Burgos",
    "Perro de Presa Canario",
    "Perro de Presa Mallorquin",
    "Peruvian Hairless Dog",
    "Peruvian Inca Orchid",
    "Petit Basset Griffon Vendeen",
    "Petit Basset Griffon Vendéen",
    "Phalène",
    "Pharaoh Hound",
    "Phu Quoc Ridgeback",
    "Picardy Spaniel",
    "Plott",
    "Plott Hound",
    "Plummer Terrier",
    "Pocket Beagle",
    "Podenco Canario",
    "Pointer",
    "Poitevin",
    "Polish Greyhound",
    "Polish Hound",
    "Polish Hunting Dog",
    "Polish Lowland",
    "Polish Lowland Sheepdog",
    "Polish Tatra Sheepdog",
    "Pomeranian",
    "Pomsky",
    "Pont-Audemer Spaniel",
    "Poodle",
    "Poodle - Standard",
    "Poodle - Toy",
    "Porcelaine",
    "Portuguese Podengo",
    "Portuguese Podengo Pequeno",
    "Portuguese Pointer",
    "Portuguese Water Dog",
    "Posavac Hound",
    "Pražský Krysarík",
    "Pudelpointer",
    "Pug",
    "Puggle",
    "Puli",
    "Pumi",
    "Pungsan Dog",
    "Pyrenean Mastiff",
    "Pyrenean Shepherd",
    "Rafeiro do Alentejo",
    "Rajapalayam",
    "Rampur Greyhound",
    "Rastreador Brasileiro",
    "Rat Terrier",
    "Ratonero Bodeguero Andaluz",
    "Ratonero Murciano de Huerta",
    "Ratonero Valenciano",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Romanian Mioritic Shepherd Dog",
    "Rottweiler",
    "Russell Terrier",
    "Russian Spaniel",
    "Russian Toy",
    "Russian Tracker",
    "Russo-European Laika",
    "Saarloos Wolfdog",
    "Sabueso Español",
    "Sabueso fino Colombiano",
    "Saint Bernard",
    "Saint-Usuge Spaniel",
    "Sakhalin Husky",
    "Saluki",
    "Samoyed",
    "Sapsali",
    "Šarplaninac",
    "Schapendoes",
    "Schillerstövare",
    "Schipperke",
    "Schnoodle",
    "Schweizer Laufhund",
    "Schweizerischer Niederlaufhund",
    "Scotch Collie",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Segugio Italiano",
    "Seppala Siberian Sleddog",
    "Serbian Hound",
    "Serbian Tricolour Hound",
    "Seskar Seal Dog",
    "Shar Pei",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Shikoku",
    "Shiloh Shepherd",
    "Siberian Husky",
    "Silken Windhound",
    "Silky Terrier",
    "Sinhala Hound",
    "Skye Terrier",
    "Sloughi",
    "Slovak Cuvac",
    "Slovakian Wirehaired Pointer",
    "Slovenský Kopov",
    "Smålandsstövare",
    "Small Greek Domestic Dog",
    "Small Munsterlander Pointer",
    "Smooth Fox Terrier",
    "Soft Coated Wheaten Terrier",
    "Soft-Coated Wheaten Terrier",
    "South Russian Ovcharka",
    "Southern Hound",
    "Spanish Mastiff",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Sporting Lucas Terrier",
    "Springer Spaniel - English",
    "St. Bernard",
    "St. John's water dog",
    "Stabyhoun",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Stephens Cur",
    "Styrian Coarse-haired Hound",
    "Sussex Spaniel",
    "Swedish Lapphund",
    "Swedish Vallhund",
    "Tahltan Bear Dog",
    "Taigan",
    "Taiwan Dog",
    "Talbot",
    "Tamaskan Dog",
    "Teddy Roosevelt Terrier",
    "Telomian",
    "Tenterfield Terrier",
    "Terceira Mastiff",
    "Thai Bangkaew Dog",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Tornjak",
    "Tosa",
    "Toy Bulldog",
    "Toy Fox Terrier",
    "Toy Manchester Terrier",
    "Toy Trawler Spaniel",
    "Transylvanian Hound",
    "Treeing Cur",
    "Treeing Tennessee Brindle",
    "Treeing Walker Coonhound",
    "Trigg Hound",
    "Tweed Water Spaniel",
    "Tyrolean Hound",
    "Valencian Ratter",
    "Vanjari Hound",
    "Villano de Las Encartaciones",
    "Villanuco de Las Encartaciones",
    "Vizsla",
    "Volpino Italiano",
    "Weimaraner",
    "Welsh Corgi, Cardigan",
    "Welsh Corgi, Pembroke",
    "Welsh Sheepdog",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier",
    "West Siberian Laika",
    "Westphalian Dachsbracke",
    "Wetterhoun",
    "Whippet",
    "White Shepherd",
    "Wire Fox Terrier",
    "Wirehaired Pointing Griffon",
    "Wirehaired Vizsla",
    "Xiasi Dog",
    "Xoloitzcuintli",
    "Yorkipoo",
    "Yorkshire Terrier"]

  constructor(http: HttpClient, @Inject('BASE_URL') baseUrl: string, title: Title, formBuilder: FormBuilder, validation: Validation) {

    this.http = http;
    this.baseUrl = baseUrl;
    this.formBuilder = formBuilder;
    this.validation = validation;

    title.setTitle("Membership Form - Clifton AC");

    this.form = formBuilder.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      emailAddress: ['', [Validators.required, Validators.email]],
      phoneNumber: ['', [Validators.required]],
      dogName: ['', [Validators.required, Validators.minLength(2)]],
      breed: ['', [Validators.required]],
      dogDateOfBirth: ['', [Validators.required]],
      message: [''],
      recaptcha: [null, Validators.required]
    });
  }

  get recaptchaSize(): 'normal' | 'compact' {
    return (window.innerWidth < 385) ? 'compact' : 'normal';
  }

  public sendMessage() {

    if (!this.form.valid) {

      return;
    }

    var options = {
      headers: new HttpHeaders({
        'recaptcha-response': this.form.get('recaptcha').value
      })
    };

    this.sending = true;

    this.http
      .post(this.baseUrl + "api/message/memberform", this.form.value, options)
      .subscribe(
        result => {

          this.sending = false;
          this.messageSent = true;
        },
        error => {

          this.sending = false;
          this.messageSent = false;
        });
  }
}

enum FormStatus {
  ShowForm,
  MessageSent,
  MessageFailed
}
